version: '3.4'

services:
  wunderdb:
    image: ghcr.io/tanmoysg/wdb-retro:latest
    container_name: wunderdb
    ports:
      - 5002:5002
    environment:
      - PORT=123
      - SERVER=smtp.server.com
      - PASSWORD=password
      - SENDER=sender
    volumes:
      - ./clusters:/app/clusters
    networks:
      - wundernetwork
    

  wunderdash:
    image: ghcr.io/tanmoysg/wunderdash:latest
    container_name: wunderdash
    environment:
      NODE_ENV: production
      WDB_URL: http://localhost:5002
    ports:
      - 3000:3000
    networks:
      - wundernetwork

networks:
  wundernetwork:
    driver: bridge
